### ISSUE TITLE
APIs will be imported with their states

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-apim-tooling#105]
**Description:**
Imported APIs will be in Created, Published or Prototyped states in the second environment according to their states in the first environment. However, according to the [documentation](https://docs.wso2.com/display/AM300/Migrating+the+APIs+and+Applications+to+a+Different+Environment#MigratingtheAPIsandApplicationstoaDifferentEnvironment-ImportinganAPI), those APIs should be in the Created state.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Export few APIs which are in Created, Published and Prototyped states.
2. Import them into another environment.

**Related Issues:**

**Comment by dushaniw** [comment]
Could you please attach the link to the documentation as well?

**Comment by ThaminduDilshan** [comment]
Sure. I added

**Comment by dushaniw** [comment]
Previously the APIs were imported the only to the CREATED state. But in order to support CI/CD flow via the import-export tool, we have extended the capability to change the state from initial state CREATED to the target status of the importing API, if it is directly reachable from the CREATED state. Hence, we need to alter the documentation [1] an [2] to remove the following warning 
`
When you import an API, regardless the status of the imported API it will be added with the created state and you need to sign in to the Publisher and publish the API.` 

[1] https://docs.wso2.com/display/AM300/Migrating+the+APIs+and+Applications+to+a+Different+Environment#MigratingtheAPIsandApplicationstoaDifferentEnvironment-ImportinganAPI
[2] https://docs.wso2.com/display/AM260/Migrating+the+APIs+and+Applications+to+a+Different+Environment

@Mariangela @ruthryi  please note.

**Comment by Mariangela** [comment]
Updated this in API-M 2.6.0 [1]

[1] https://docs.wso2.com/display/AM260/Migrating+the+APIs+and+Applications+to+a+Different+Environment

**Comment by dushaniw** [comment]
Thanks @Mariangela
