### ISSUE TITLE
Login failure when executing the export-api command

### ISSUE THREAD

**Issue by pubudu538** [wso2/product-apim-tooling#106]
**Description:**
When export-api command is executed as below, it gives an error when credentials are given to logged into the system.

c:\Program Files\WSO2\apimcli>apimcli export-api -n testapi -v v2 -r admin -e localhost
Login to localhost
Username:admin
Password:apimcli: Error getting credentials Reason: The handle is invalid.
Exit status 1

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
windows

**Steps to reproduce:**

**Related Issues:**

**Comment by Rietty** [comment]
Have also been running into this issue. Can't do `apictl login dev -k`.

**Comment by ecostanzi** [comment]
I also ran into this issue using apictl 3.1.0-alpha. 

```
→ ~\Downloads\wso2\apictl› .\apictl.exe login javadev -k
Username:admin
Password:Error occurred while login :  The handle is invalid.
```

**Comment by 1akshitha** [comment]
As a workaround, you can use following command to log in to the environment.
```apictl login dev -u admin -p admin -k```

**Comment by kasvith** [comment]
this seems to be related to `terminal` package provided by stdlib
https://github.com/wso2/product-apim-tooling/blob/15dd1d607c1254f987ea9b5c08ae34328f888b16/import-export-cli/cmd/login.go#L107

This is happening because mainly, windows do not provide the same file descriptors like Unix. In unix/linux fd 0 is known as stdin, but its not same in windows

Fix would be replacing `pass, err := terminal.ReadPassword(0)` with `pass, err := terminal.ReadPassword(syscall.Stdin)` as per https://github.com/golang/go/issues/11914

**Comment by kasvith** [comment]
this seems to be related to `terminal` package provided by stdlib
https://github.com/wso2/product-apim-tooling/blob/15dd1d607c1254f987ea9b5c08ae34328f888b16/import-export-cli/cmd/login.go#L107

This is happening because mainly, windows do not provide the same file descriptors like Unix. In unix/linux fd 0 is known as stdin, but it's not same in windows

Fix would be replacing `pass, err := terminal.ReadPassword(0)` with `pass, err := terminal.ReadPassword(int(syscall.Stdin))` as per https://github.com/golang/go/issues/11914

This fix will work on
- Command Prompt
- Powershell
- Powershell Core

But this will not work in TTYs like **GitBash**. This is because in GitBash Stdin is handled differently(OS is Windows, so go will try to use windows methods which won't support by GitBash)

**This is an edge case,** to get over with that, we can use https://github.com/moby/moby/tree/master/pkg/term instead of `crypto/terminal`

**Comment by AyandaMak** [comment]
Hi there, I'm running windows but I cannot find the login.go file in any directories to make the change mentioned above. It's not located it apictl-3.0.1. Some help will be appreciated.

**Comment by 1akshitha** [comment]
@AyandaMak Please find the login.go for 3.0.1 version in the following location.
https://github.com/wso2/product-apim-tooling/blob/v3.0.1/import-export-cli/cmd/login.go#L107

**Comment by AyandaMak** [comment]
@1akshitha Sorry for not clarifying but I actually meant I cannot locate the file on my local machine where I'm meant to make the change.

**Comment by kasvith** [comment]
@AyandaMak source files are not shipped with executable :) please download code and follow build instructions

But this fix has been applied to https://github.com/wso2/product-apim-tooling/releases/tag/v3.1.0 so you can just download this version and use it without modifications
