### ISSUE TITLE
apictl is not working on the alpine based containers

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-apim-tooling#130]
**Description:**
When we download the linux distribution from the site and then run it on a container which is based on alpine linux it gives syntax errors. I think we will need to have the seperate distribution for this.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.0.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by RameshaKaru** [comment]
The apictl distribution for linux-32-bit is working in the alpine containers. apictl linux-64-bit distribution built from a linux machine does not seem to be working in alpine containers, although it works in normal linux machines. Also apictl linux-64-bit distributions built from a mac machine seems to be working. Hence, please use apictl linux-32-bit distribution in the alpine containers for the moment

**Comment by uvindra** [comment]
This maybe a common issue for Go executables as outlined in https://forum.golangbridge.org/t/why-isnt-the-go-executable-compiled-statically/15781

The use of _net_ and _os_ level packages will lead to dynamic linking, which on most Linux distributions will result on linking with **glibc**. Since Alpine favours using **musl** instead, this will lead to binary incompatibility. 

Need to try the solution for using the _netgo_ and _usergo_ build tags when building to see if it solves the issue

**Comment by wasuradananjith** [comment]
Fixed via https://github.com/wso2/product-apim-tooling/pull/808
