### ISSUE TITLE
Support custom throttling policies from apictl

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim-tooling#329]
**Description:**
Custom application/subscription, advanced policies import/export are currently not supported. We need to support it.

**Comment by wasuradananjith** [comment]
We will be addressing only the shortcomings and inconsistencies identified in the current behaviour as mentioned below.
The changes will be done related to the three (3) main throttling policies. 
1. **Advanced Throttling Policies**
    1. Modifications related to **API/Product Level Throttling Policies**
        - When we try to import an API/API Product with an Advanced Throttling Policy that has been assigned to the  API/API Product, which is not currently available in the API Manager, an error was displayed earlier. But with this PR, now you will receive an error and the import will be failed.
    2. Modifications related to **Resource Level Throttling Policies**
        - No changes needed to be done.
2. **Application-level Throttling Tiers/Policies**
    - When we try to import an Application, if the Application-level Throttling Tier/Policy is not available in the API Manager instance, the application was imported to that instance, which was wrong. But with this PR, now you will receive an error if you try to do that and the import will be failed.
3. **Subscription-level Throttling Tiers/Policies**
    - When we export an API/API Product with a Subscription-level Throttling Tier/Policy using the API Controller, the throttling policy **details** will be included in the api.yaml file inside the exported directory as an array. But with this PR, the throttling policy **names** will be exported as an array instead of all the **details** of tiers.
    - When we try to import an API/API Product, if any of the Subscription-level Throttling Tiers/Policies were not available in the API Manager, the API Manager ignored it and imported the API/API Product with the existing Subscription-level Throttling Tiers/Policies. But with this PR, now you will receive an error if you are trying to import an API/API Product with the Subscription-level Throttling Tiers/Policies if any of those are not available in the API Manager instance and the import will be failed.

Refer [1] to understand more about the approach.

Since importing/exporting throttling policies is a one-time procedure per environment, we decided not to support full export/import functionality with new commands.

[1] http://wso2-oxygen-tank.10903.n7.nabble.com/APIM-Support-to-Import-Export-Throttling-Policies-Using-the-API-Controller-td162176.html
