### ISSUE TITLE
Support shared custom mediation policies from APICTL

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim-tooling#330]
**Description:**
Currently, we support only API specific custom mediation policies while import/export APIs.
We need to support shared mediation policies too.

**Comment by wasuradananjith** [comment]
Adding to the above, according to the changes in [1], it has been suggested to add multiple IN/OUT/FAULT sequences rather than having one inside each folder as shown in the structure of [1]. The sequence(s) that should be considered in the runtime will be anyway marked in the api.yaml inside the API DTO. 

[1] https://github.com/wso2/carbon-apimgt/pull/9406

**Comment by wasuradananjith** [comment]
The API specific mediations can be imported/exported already since it was implemented via [1]. But we need to fix the issue when importing/exporting a <b>shared/global</b> mediation attached to an API. We need to verify and fix the below scenarios.

<b>Scenario 1</b>
<ol>
<li> A person add a mediation from the Admin Portal.</li>
<li> Attach the above-added mediation to an API through the Publisher Portal.</li>
<li> Export the API using APICTL </li>
<li> Now need to check whether the mediation has been exported. If not so we need to fix it.</li>
</ol>

<b>Scenario 2</b>
<ol>
<li> Import the above-exported API to another environment that does not have that global mediation.</li>
<li> Need to check whether the API is getting imported with the mediation. If not so, we need a way to add that sequence to the environment and then assign it to the API during the runtime.</li>
</ol>

[1] https://github.com/wso2/carbon-apimgt/pull/9480

**Comment by wasuradananjith** [comment]
All the use cases have been revamped and fixed via [1]. Hence, closing the issue.

[1] https://github.com/wso2/api-manager/issues/223
