### ISSUE TITLE
[Improvement] Support prototype implementation in a external params file as we support for endpoint configurations.

### ISSUE THREAD

**Issue by Chamindu36** [wso2/product-apim-tooling#475]
**Description:**
Current APICTL supports being able to specify the endpoint externally to the swagger via an external param.yaml file. In a scenario, a user wants import API with a prototype implementation and test that API in PROTOTYPED state and then import the API with the actual endpoint with CREATED or PUBLISHED state, current APICTL won't be able to facilitate this scenario.

To support this  APICTL needs to be able to externalize the Prototype implementation in a param file as it does for the endpoint configurations. Then the user can use the same Swagger with different param files to import with either prototype implementation or actual endpoint implementation.

**Suggested Labels:**
3.x.x, Type/Improvement

**Comment by wasuradananjith** [comment]
If we export a prototyped API from APIM 4.0.0 and try to import it again to another instance, this works as expected. Also, we do not have a plan to support dev first support for prototyped APIs which will be a more complicated scenario. 

Since the basic export/import is working for PROTOTYPED APIs in APIM 4.0.0 and APICTL 4.0.0, we will be closing this issue.
