### ISSUE TITLE
wso2 am 3.0.0 and apictl 3.0.1 does not allow to add env | Mac OS

### ISSUE THREAD

**Issue by dnellutla** [wso2/product-apim-tooling#630]
**Description:**
apictl add env command gives the below error:

./apictl add-env -e local \
--apim  https://localhost:9443
Execute 'apictl add-env --help' for more info.
apictl: Error adding environment Reason: endpoints cannot be blank
Exit status 1

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
Mac OS

**Steps to reproduce:**

Run the above command

**Related Issues:**

**Comment by npamudika** [comment]
Hey,

Since you are using the APICTL 3.0.1 version, you need to try a command like this.

`
apictl add-env -e local --registration https://localhost:9443/client-registration/v0.15/register --apim https://localhost:9443 --token https://localhost:8243/token
`

Can you try with the above and see?

Please follow https://apim.docs.wso2.com/en/3.0.0/learn/api-controller/getting-started-with-wso2-api-controller/#add-an-environment for more details.

Thanks,
Naduni

**Comment by dnellutla** [comment]
Thank you.
