### ISSUE TITLE
Use comprehensive (English) language.

### ISSUE THREAD

**Issue by p1wdotnl** [wso2/product-apim-tooling#851]
**Description:**
The import/export tool uses incomprehensive language. Sure, the tool is part of the API Manager family. But it is suppose to be used "abroad", as a push mechanism that exports, not at the API Manager server to perform a pull/import.

You do understand that it is ridiculous that I have to "import" an API configuration to move it to one of the remote API Managers and an "export" to fetch a configuration from a remote location?

**Affected Product Version:**
As far as I know: any up to and including 4.0

**Steps to reproduce:**

- apictl import
- apictl import-api
- apictl import-app
- apictl export
- apictl export-api
- apictl export-apis
- apictl export-app

**Comment by wasuradananjith** [comment]
Hi @p1wdotnl,

According to what you have stated above, the order of the steps mentioned is incorrect.

1. Firstly, you need to export an API/API Product/Application from one API Manager instance using apictl. Here, you will receive a zipped archive where you can store anywhere (including in a remote location)
2. Next, you can import the previously exported archive to another API Manager instance using apictl.

In English, generally "import" means "the act of bringing a product or service into one country from another" [1]. Here, in the API Manager context, the term "import" defines the process of bringing APIs/API Products/Applications artifacts from one environment to another. We can't just simply say that this is a process of just "pushing" artifacts because the underlying implementation of the import command does various tasks such as importing configurations, OAS definitions, etc instead of just pushing the artifact.

Moreover, we have used this command from the oldest API Manager Tooling version [2]. Hence, we think this wording is aligning with the overall task of apictl which is moving/migrating APIs/API Products/Applications from one environment to another.

[1] https://www.oxfordlearnersdictionaries.com/definition/english/import_1?q=import
[2] https://github.com/wso2/product-apim-tooling/releases/tag/v1.0.0

**Comment by npamudika** [comment]
Please do reopen, if you need further clarifications on this.
