### ISSUE TITLE
apictl certificate has expired

### ISSUE THREAD

**Issue by sureshachary** [wso2/product-apim-tooling#862]
$_apictl import api --file ./PetstoreAPI --environment dev_
Login to APIM in dev
Username:admin
Password:
apictl: Error in connecting. Reason: Post "https://localhost:9443/client-registration/v0.17/register": x509: certificate has expired or is not yet valid: current time 2022-01-26T23:07:52+05:30 is after 2022-01-25T07:30:43Z
Exit status 1

How to get rid of this error? Using apictl-4.0.1 and wso2am-4.0.0

**Comment by npamudika** [comment]
Hi @sureshachary,

You can run the commands with **-k** flag as a workaround.

Thanks,
Naduni

**Comment by wasuradananjith** [comment]
We have fixed this in the new apictl version to be released (apictl 4.1.0-M4) [1].

We will not be updating the certificates in the old APIM/apictl versions, because if we update the trust stores and all, the existing user certs will get overwritten by the new ones. Hence, for example, in apictl 4.0.0, you need to generate your own cert and add it to the certs directory as mentioned in [2]. Or else, as @npamudika mentioned you can use -k flag.

Closing the issue since the solution was explained.

[1] https://github.com/wso2/product-apim-tooling/issues/868
[2] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller/#import-ssl-certificates-for-secure-http-communication-with-wso2-api-m
